-- GENERATED FILE — do not edit by hand.
-- Source: packages/shared/src/templates/*.data.json
-- Regenerate: node supabase/seed/generate.mjs
-- Seeds the 22+ V1 templates and 4 bundles. Idempotent (upsert by id).

-- GENERATED FILE — do not edit by hand.
-- Source: packages/shared/src/templates/templates.data.json
-- Regenerate: node supabase/seed/generate.mjs

insert into public.templates
  (id, name, domain, category, plain_description, structure_type, sections, fields, missing_detail_rules, fill_from_profile, recommendation_reason, related_document_ids, advice_boundary, brandable, flags, display_order)
values
  ('11111111-0000-4000-8000-000000000001', 'Resume', 'employment', 'Job application', 'A clear, modern resume that puts your strongest experience first.', 'structured_form', '[{"key":"summary","name":"Professional Summary","description":"A 2–3 line snapshot of who you are and what you offer.","is_required":true,"order":0},{"key":"experience","name":"Work Experience","description":"Roles, dates, and achievements in reverse chronological order.","is_required":true,"order":1},{"key":"education","name":"Education & Qualifications","description":"Degrees, certificates, and relevant training.","is_required":true,"order":2},{"key":"skills","name":"Key Skills","description":"The capabilities most relevant to the target role.","is_required":true,"order":3},{"key":"referees","name":"Referees","description":"Contacts who can speak to your work.","is_required":false,"order":4}]'::jsonb, '[{"name":"full_name","type":"text","label":"Full name","placeholder":"Jordan Smith","fillFromProfile":"display_name","required":true},{"name":"target_role","type":"text","label":"Role you''re applying for","placeholder":"Operations Manager","required":true},{"name":"phone","type":"text","label":"Phone","placeholder":"0400 000 000","fillFromProfile":"phone","required":false}]'::jsonb, '[{"field":"target_role","reason":"TED tailors the summary and skills to the role you''re targeting.","is_required":true},{"field":"referees","reason":"Referees are optional — you can add them later.","is_required":false}]'::jsonb, '{"full_name":"display_name","phone":"phone"}'::jsonb, 'A resume is the core document for any job application.', '["11111111-0000-4000-8000-000000000002"]'::jsonb, 'none', false, '{}'::jsonb, 0),
  ('11111111-0000-4000-8000-000000000002', 'Cover Letter', 'employment', 'Job application', 'A tailored cover letter that connects your experience to the role.', 'compose', '[{"key":"opening","name":"Opening & Role","description":"Who you are and the role you''re applying for.","is_required":true,"order":0},{"key":"fit","name":"Why You Fit","description":"The experience and strengths that match the role.","is_required":true,"order":1},{"key":"motivation","name":"Why This Employer","description":"What draws you to this organisation specifically.","is_required":true,"order":2},{"key":"closing","name":"Closing & Next Step","description":"A confident sign-off inviting an interview.","is_required":true,"order":3}]'::jsonb, '[{"name":"full_name","type":"text","label":"Full name","placeholder":"Jordan Smith","fillFromProfile":"display_name","required":true},{"name":"target_role","type":"text","label":"Role you''re applying for","placeholder":"Operations Manager","required":true},{"name":"company","type":"text","label":"Employer name","placeholder":"Acme Pty Ltd","required":true}]'::jsonb, '[{"field":"company","reason":"TED personalises the letter to the employer you name.","is_required":true}]'::jsonb, '{"full_name":"display_name"}'::jsonb, 'A cover letter lifts your application above a resume alone.', '["11111111-0000-4000-8000-000000000001"]'::jsonb, 'none', false, '{}'::jsonb, 1),
  ('11111111-0000-4000-8000-000000000003', 'Job-search Action Checklist', 'employment', 'Job application', 'A step-by-step checklist to keep your job search on track.', 'checklist', '[{"key":"items","name":"Action Items","description":"Concrete steps with suggested timing.","is_required":true,"order":0}]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{}'::jsonb, 'A checklist turns a daunting search into manageable steps.', '[]'::jsonb, 'none', false, '{}'::jsonb, 2),
  ('11111111-0000-4000-8000-000000000004', 'Interview Preparation Questions', 'employment', 'Interview', 'Likely interview questions with prompts to prepare strong answers.', 'compose', '[{"key":"about_you","name":"Questions About You","description":"Strengths, weaknesses, and motivation questions.","is_required":true,"order":0},{"key":"role_specific","name":"Role-specific Questions","description":"Technical and scenario questions for this role.","is_required":true,"order":1},{"key":"your_questions","name":"Questions to Ask Them","description":"Smart questions that show genuine interest.","is_required":true,"order":2}]'::jsonb, '[{"name":"target_role","type":"text","label":"Role","placeholder":"Operations Manager","required":true}]'::jsonb, '[{"field":"target_role","reason":"Questions are tailored to the role you''re interviewing for.","is_required":true}]'::jsonb, '{}'::jsonb, 'Preparation is the biggest predictor of interview success.', '["11111111-0000-4000-8000-000000000005"]'::jsonb, 'none', false, '{}'::jsonb, 3),
  ('11111111-0000-4000-8000-000000000005', 'Interview Script', 'employment', 'Interview', 'A personal script of answers to the questions you''re most likely to face.', 'compose', '[{"key":"intro","name":"Your Introduction","description":"A crisp 60-second answer to ''tell me about yourself''.","is_required":true,"order":0},{"key":"stories","name":"Achievement Stories","description":"STAR-format examples of your best work.","is_required":true,"order":1},{"key":"tricky","name":"Tricky Questions","description":"Honest, prepared answers to harder questions.","is_required":true,"order":2}]'::jsonb, '[{"name":"target_role","type":"text","label":"Role","placeholder":"Operations Manager","required":true}]'::jsonb, '[]'::jsonb, '{}'::jsonb, 'A script lets you walk in calm and ready.', '["11111111-0000-4000-8000-000000000004"]'::jsonb, 'none', false, '{}'::jsonb, 4),
  ('11111111-0000-4000-8000-000000000006', 'Job Follow-up Email', 'employment', 'Interview', 'A polite, professional follow-up after applying or interviewing.', 'compose', '[{"key":"thanks","name":"Thanks & Recap","description":"Thank them and recap your interest.","is_required":true,"order":0},{"key":"value","name":"Reinforce Your Value","description":"A brief reminder of why you''re a strong fit.","is_required":true,"order":1},{"key":"next","name":"Next Steps","description":"A gentle nudge on timing.","is_required":false,"order":2}]'::jsonb, '[{"name":"contact_name","type":"text","label":"Who you''re writing to","placeholder":"Priya (Hiring Manager)","required":false}]'::jsonb, '[]'::jsonb, '{}'::jsonb, 'A timely follow-up keeps you front of mind.', '[]'::jsonb, 'light', false, '{}'::jsonb, 5),
  ('11111111-0000-4000-8000-000000000007', 'Pay-rise Request & Conversation Script', 'employment', 'Career', 'A written request and talking points to ask for a pay rise with confidence.', 'compose', '[{"key":"case","name":"Your Case","description":"The evidence and achievements that justify a rise.","is_required":true,"order":0},{"key":"ask","name":"The Ask","description":"A clear, specific figure or range.","is_required":true,"order":1},{"key":"script","name":"Conversation Script","description":"What to say in the meeting, including responses to pushback.","is_required":true,"order":2}]'::jsonb, '[{"name":"current_role","type":"text","label":"Your role","placeholder":"Operations Manager","required":true}]'::jsonb, '[]'::jsonb, '{}'::jsonb, 'Coming prepared makes the conversation far easier.', '["11111111-0000-4000-8000-000000000008"]'::jsonb, 'light', false, '{}'::jsonb, 6),
  ('11111111-0000-4000-8000-000000000008', 'Promotion Case', 'employment', 'Career', 'A structured case for why you''re ready for the next role.', 'compose', '[{"key":"impact","name":"Impact to Date","description":"Results that show you''re already operating at the next level.","is_required":true,"order":0},{"key":"readiness","name":"Readiness","description":"Skills and scope you''ve grown into.","is_required":true,"order":1},{"key":"proposal","name":"The Proposal","description":"The role, title, and responsibilities you''re seeking.","is_required":true,"order":2}]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{}'::jsonb, 'A clear case makes it easy for your manager to say yes.', '["11111111-0000-4000-8000-000000000007"]'::jsonb, 'light', false, '{}'::jsonb, 7),
  ('11111111-0000-4000-8000-000000000009', 'Personal Statement', 'education', 'Application', 'A compelling personal statement for study or scholarship applications.', 'compose', '[{"key":"motivation","name":"Your Motivation","description":"Why this course or program matters to you.","is_required":true,"order":0},{"key":"background","name":"Relevant Background","description":"Experience and achievements that prepared you.","is_required":true,"order":1},{"key":"goals","name":"Your Goals","description":"What you intend to do with the opportunity.","is_required":true,"order":2}]'::jsonb, '[{"name":"program","type":"text","label":"Course or program","placeholder":"Master of Public Health","required":true}]'::jsonb, '[{"field":"program","reason":"The statement is tailored to the program you name.","is_required":true}]'::jsonb, '{}'::jsonb, 'The personal statement is often the deciding factor.', '["11111111-0000-4000-8000-000000000010"]'::jsonb, 'none', false, '{}'::jsonb, 0),
  ('11111111-0000-4000-8000-000000000010', 'Application Letter — Education', 'education', 'Application', 'A formal letter to accompany an education application.', 'compose', '[{"key":"intro","name":"Introduction","description":"The program and your purpose for writing.","is_required":true,"order":0},{"key":"suitability","name":"Your Suitability","description":"Why you''re a strong candidate.","is_required":true,"order":1},{"key":"close","name":"Closing","description":"A courteous sign-off.","is_required":true,"order":2}]'::jsonb, '[{"name":"institution","type":"text","label":"Institution","placeholder":"University of Melbourne","required":true}]'::jsonb, '[]'::jsonb, '{}'::jsonb, 'A polished letter sets the right tone for your application.', '["11111111-0000-4000-8000-000000000009"]'::jsonb, 'none', false, '{}'::jsonb, 1),
  ('11111111-0000-4000-8000-000000000011', 'Reference Request', 'education', 'Application', 'A respectful request asking someone to be your referee.', 'compose', '[{"key":"ask","name":"The Request","description":"A clear, polite ask with context.","is_required":true,"order":0},{"key":"details","name":"Helpful Details","description":"What the reference is for and the deadline.","is_required":true,"order":1}]'::jsonb, '[{"name":"referee_name","type":"text","label":"Referee''s name","placeholder":"Dr Lee","required":false}]'::jsonb, '[]'::jsonb, '{}'::jsonb, 'Making it easy to say yes gets you a stronger reference.', '[]'::jsonb, 'none', false, '{}'::jsonb, 2),
  ('11111111-0000-4000-8000-000000000012', 'Business Email', 'business', 'Communication', 'A clear, professional email for any business situation.', 'compose', '[{"key":"subject","name":"Subject & Greeting","description":"A specific subject line and appropriate greeting.","is_required":true,"order":0},{"key":"body","name":"Message","description":"The core message, structured for easy reading.","is_required":true,"order":1},{"key":"action","name":"Call to Action","description":"What you need and by when.","is_required":true,"order":2}]'::jsonb, '[{"name":"recipient","type":"text","label":"Recipient","placeholder":"the supplier","required":false}]'::jsonb, '[]'::jsonb, '{}'::jsonb, 'The right email gets a faster, better response.', '[]'::jsonb, 'none', true, '{}'::jsonb, 0),
  ('11111111-0000-4000-8000-000000000013', 'Workplace Policy', 'business', 'Policy', 'A clear workplace policy that sets expectations for your team.', 'compose', '[{"key":"purpose","name":"Purpose & Scope","description":"Why the policy exists and who it covers.","is_required":true,"order":0},{"key":"policy","name":"Policy Statements","description":"The rules and expectations themselves.","is_required":true,"order":1},{"key":"responsibilities","name":"Responsibilities","description":"Who is responsible for what.","is_required":true,"order":2},{"key":"breach","name":"Breaches","description":"What happens if the policy isn''t followed.","is_required":false,"order":3}]'::jsonb, '[{"name":"policy_topic","type":"text","label":"Policy topic","placeholder":"Remote work","required":true},{"name":"business_name","type":"text","label":"Business name","placeholder":"Acme Pty Ltd","fillFromProfile":"business_name","required":false}]'::jsonb, '[{"field":"policy_topic","reason":"TED writes the policy around the topic you choose.","is_required":true}]'::jsonb, '{"business_name":"business_name"}'::jsonb, 'A written policy prevents misunderstandings before they happen.', '["11111111-0000-4000-8000-000000000014"]'::jsonb, 'light', true, '{}'::jsonb, 1),
  ('11111111-0000-4000-8000-000000000014', 'Standard Operating Procedure', 'business', 'Operations', 'A step-by-step SOP so a task is done the same way every time.', 'compose', '[{"key":"overview","name":"Overview","description":"What the procedure is for and when to use it.","is_required":true,"order":0},{"key":"steps","name":"Procedure Steps","description":"Numbered, unambiguous steps.","is_required":true,"order":1},{"key":"roles","name":"Roles & Responsibilities","description":"Who does each part.","is_required":false,"order":2}]'::jsonb, '[{"name":"task_name","type":"text","label":"Task or process","placeholder":"Onboarding a supplier","required":true}]'::jsonb, '[{"field":"task_name","reason":"The SOP is built around the specific task you name.","is_required":true}]'::jsonb, '{"business_name":"business_name"}'::jsonb, 'An SOP makes quality and training repeatable.', '["11111111-0000-4000-8000-000000000013"]'::jsonb, 'none', true, '{}'::jsonb, 2),
  ('11111111-0000-4000-8000-000000000015', 'Offer Letter', 'business', 'Hiring', 'A professional letter offering a role, in writing.', 'compose', '[{"key":"offer","name":"The Offer","description":"Role, start date, and a warm welcome.","is_required":true,"order":0},{"key":"terms","name":"Key Terms","description":"Remuneration, hours, and location.","is_required":true,"order":1},{"key":"conditions","name":"Conditions","description":"Any conditions of the offer (e.g. references).","is_required":false,"order":2},{"key":"acceptance","name":"Acceptance","description":"How and by when to accept.","is_required":true,"order":3}]'::jsonb, '[{"name":"candidate_name","type":"text","label":"Candidate name","placeholder":"Jordan Smith","required":true},{"name":"role_title","type":"text","label":"Role title","placeholder":"Operations Manager","required":true},{"name":"business_name","type":"text","label":"Business name","placeholder":"Acme Pty Ltd","fillFromProfile":"business_name","required":true}]'::jsonb, '[{"field":"role_title","reason":"The offer needs the role you''re offering.","is_required":true},{"field":"candidate_name","reason":"The offer is addressed to the candidate.","is_required":true}]'::jsonb, '{"business_name":"business_name"}'::jsonb, 'A written offer confirms the role and protects both sides.', '["11111111-0000-4000-8000-000000000016"]'::jsonb, 'high-stakes', true, '{}'::jsonb, 3),
  ('11111111-0000-4000-8000-000000000016', 'Terms of Employment', 'business', 'Hiring', 'A plain-English summary of the terms of an employment arrangement.', 'compose', '[{"key":"parties","name":"Parties & Role","description":"Who''s employing whom, and in what role.","is_required":true,"order":0},{"key":"pay","name":"Pay & Hours","description":"Remuneration, hours, and entitlements.","is_required":true,"order":1},{"key":"obligations","name":"Obligations","description":"Key responsibilities and conduct expectations.","is_required":true,"order":2},{"key":"ending","name":"Ending Employment","description":"Notice periods and how the arrangement can end.","is_required":true,"order":3}]'::jsonb, '[{"name":"business_name","type":"text","label":"Business name","placeholder":"Acme Pty Ltd","fillFromProfile":"business_name","required":true}]'::jsonb, '[]'::jsonb, '{"business_name":"business_name"}'::jsonb, 'Clear terms prevent disputes down the track.', '["11111111-0000-4000-8000-000000000015"]'::jsonb, 'high-stakes', true, '{}'::jsonb, 4),
  ('11111111-0000-4000-8000-000000000017', 'Induction Manual', 'business', 'Onboarding', 'A welcoming manual that helps a new hire get up to speed.', 'compose', '[{"key":"welcome","name":"Welcome","description":"A warm introduction to the team and mission.","is_required":true,"order":0},{"key":"how_we_work","name":"How We Work","description":"Tools, hours, and ways of working.","is_required":true,"order":1},{"key":"policies","name":"Key Policies","description":"The policies a new hire must know on day one.","is_required":true,"order":2},{"key":"contacts","name":"Who''s Who","description":"Key people and how to reach them.","is_required":false,"order":3}]'::jsonb, '[{"name":"business_name","type":"text","label":"Business name","placeholder":"Acme Pty Ltd","fillFromProfile":"business_name","required":false}]'::jsonb, '[]'::jsonb, '{"business_name":"business_name"}'::jsonb, 'A good induction makes new hires productive faster.', '["11111111-0000-4000-8000-000000000018"]'::jsonb, 'none', true, '{}'::jsonb, 5),
  ('11111111-0000-4000-8000-000000000018', 'Onboarding Checklist', 'business', 'Onboarding', 'Everything to set up before and during a new hire''s first weeks.', 'checklist', '[{"key":"items","name":"Onboarding Tasks","description":"Pre-start, day one, and first-month tasks.","is_required":true,"order":0}]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{}'::jsonb, 'A checklist means nothing important gets missed.', '["11111111-0000-4000-8000-000000000017"]'::jsonb, 'none', false, '{}'::jsonb, 6),
  ('11111111-0000-4000-8000-000000000019', 'Performance Review', 'business', 'People', 'A balanced, constructive performance review.', 'compose', '[{"key":"summary","name":"Overall Summary","description":"A fair summary of the period under review.","is_required":true,"order":0},{"key":"strengths","name":"Strengths","description":"What''s going well, with examples.","is_required":true,"order":1},{"key":"development","name":"Areas for Development","description":"Where to grow, framed constructively.","is_required":true,"order":2},{"key":"goals","name":"Goals for Next Period","description":"Clear, measurable goals.","is_required":true,"order":3}]'::jsonb, '[{"name":"employee_name","type":"text","label":"Employee name","placeholder":"Jordan Smith","required":false}]'::jsonb, '[]'::jsonb, '{"business_name":"business_name"}'::jsonb, 'A structured review keeps feedback fair and useful.', '[]'::jsonb, 'light', true, '{}'::jsonb, 7),
  ('11111111-0000-4000-8000-000000000020', 'Meeting Minutes / Briefing', 'business', 'Communication', 'A clear record of a meeting''s decisions and actions.', 'compose', '[{"key":"attendees","name":"Attendees & Purpose","description":"Who was there and why.","is_required":true,"order":0},{"key":"discussion","name":"Discussion","description":"Key points raised.","is_required":true,"order":1},{"key":"decisions","name":"Decisions","description":"What was decided.","is_required":true,"order":2},{"key":"actions","name":"Action Items","description":"Who''s doing what, by when.","is_required":true,"order":3}]'::jsonb, '[]'::jsonb, '[]'::jsonb, '{"business_name":"business_name"}'::jsonb, 'Minutes turn a meeting into accountable actions.', '[]'::jsonb, 'none', true, '{}'::jsonb, 8),
  ('11111111-0000-4000-8000-000000000021', 'Service Agreement', 'business', 'Contracts', 'A plain-English agreement setting out services, payment, and terms.', 'compose', '[{"key":"parties","name":"Parties","description":"Who''s providing and receiving the service.","is_required":true,"order":0},{"key":"scope","name":"Scope of Services","description":"Exactly what will be delivered.","is_required":true,"order":1},{"key":"payment","name":"Payment Terms","description":"Fees, invoicing, and timing.","is_required":true,"order":2},{"key":"terms","name":"Terms & Termination","description":"Duration, changes, and how it can end.","is_required":true,"order":3}]'::jsonb, '[{"name":"business_name","type":"text","label":"Your business name","placeholder":"Acme Pty Ltd","fillFromProfile":"business_name","required":true},{"name":"client_name","type":"text","label":"Client name","placeholder":"Beta Co","required":true}]'::jsonb, '[{"field":"client_name","reason":"The agreement names both parties.","is_required":true}]'::jsonb, '{"business_name":"business_name"}'::jsonb, 'A written agreement protects both sides and sets expectations.', '[]'::jsonb, 'high-stakes', true, '{}'::jsonb, 9),
  ('11111111-0000-4000-8000-000000000022', 'Proposal', 'business', 'Sales', 'A persuasive proposal that wins the work.', 'compose', '[{"key":"summary","name":"Executive Summary","description":"The opportunity and your offer in brief.","is_required":true,"order":0},{"key":"understanding","name":"Understanding the Need","description":"Showing you understand the client''s problem.","is_required":true,"order":1},{"key":"solution","name":"Proposed Solution","description":"What you''ll deliver and how.","is_required":true,"order":2},{"key":"pricing","name":"Pricing & Timeline","description":"Investment and key dates.","is_required":true,"order":3},{"key":"next","name":"Next Steps","description":"How to proceed.","is_required":false,"order":4}]'::jsonb, '[{"name":"business_name","type":"text","label":"Your business name","placeholder":"Acme Pty Ltd","fillFromProfile":"business_name","required":false},{"name":"client_name","type":"text","label":"Client name","placeholder":"Beta Co","required":false}]'::jsonb, '[]'::jsonb, '{"business_name":"business_name"}'::jsonb, 'A strong proposal is the difference between a maybe and a yes.', '[]'::jsonb, 'none', true, '{}'::jsonb, 10),
  ('11111111-0000-4000-8000-000000000023', 'Budget Workbook', 'finance', 'Planning', 'A personal budget that tracks income, expenses, savings, and debt.', 'structured_form', '[{"key":"income","name":"Income","description":"All sources of money coming in.","is_required":true,"order":0},{"key":"expenses","name":"Expenses","description":"Regular and one-off spending.","is_required":true,"order":1},{"key":"savings","name":"Savings","description":"What you''re putting aside and goals.","is_required":true,"order":2},{"key":"debt","name":"Debt","description":"Balances, repayments, and interest.","is_required":false,"order":3}]'::jsonb, '[{"name":"income_salary","type":"number","label":"Salary / wages (monthly)","placeholder":"0","required":true},{"name":"income_other","type":"number","label":"Other income (monthly)","placeholder":"0","required":false},{"name":"expense_housing","type":"number","label":"Housing (monthly)","placeholder":"0","required":true},{"name":"expense_living","type":"number","label":"Living costs (monthly)","placeholder":"0","required":true},{"name":"savings_monthly","type":"number","label":"Savings (monthly)","placeholder":"0","required":false},{"name":"debt_repayment","type":"number","label":"Debt repayments (monthly)","placeholder":"0","required":false}]'::jsonb, '[{"field":"income_salary","reason":"Income is the starting point for any budget.","is_required":true}]'::jsonb, '{}'::jsonb, 'A budget gives you a clear picture and control of your money.', '[]'::jsonb, 'none', false, '{"export_format":"excel"}'::jsonb, 0)
on conflict (id) do update set
  name = excluded.name,
  domain = excluded.domain,
  category = excluded.category,
  plain_description = excluded.plain_description,
  structure_type = excluded.structure_type,
  sections = excluded.sections,
  fields = excluded.fields,
  missing_detail_rules = excluded.missing_detail_rules,
  fill_from_profile = excluded.fill_from_profile,
  recommendation_reason = excluded.recommendation_reason,
  related_document_ids = excluded.related_document_ids,
  advice_boundary = excluded.advice_boundary,
  brandable = excluded.brandable,
  flags = excluded.flags,
  display_order = excluded.display_order;

-- GENERATED FILE — do not edit by hand.
-- Source: packages/shared/src/templates/bundles.data.json
-- Regenerate: node supabase/seed/generate.mjs

insert into public.bundles
  (id, name, description, domain, template_ids, checklist_template_id, display_order)
values
  ('22222222-0000-4000-8000-000000000001', 'I need a job', 'Everything to find and land your next role.', 'employment', '["11111111-0000-4000-8000-000000000001","11111111-0000-4000-8000-000000000002","11111111-0000-4000-8000-000000000003","11111111-0000-4000-8000-000000000004","11111111-0000-4000-8000-000000000005","11111111-0000-4000-8000-000000000006","11111111-0000-4000-8000-000000000023"]'::jsonb, '11111111-0000-4000-8000-000000000003', 0),
  ('22222222-0000-4000-8000-000000000002', 'Onboard a new employee', 'Bring a new hire on board the right way.', 'business', '["11111111-0000-4000-8000-000000000015","11111111-0000-4000-8000-000000000016","11111111-0000-4000-8000-000000000017","11111111-0000-4000-8000-000000000018","11111111-0000-4000-8000-000000000012"]'::jsonb, '11111111-0000-4000-8000-000000000018', 1),
  ('22222222-0000-4000-8000-000000000003', 'Set up the basics of my business', 'The core documents every small business needs.', 'business', '["11111111-0000-4000-8000-000000000013","11111111-0000-4000-8000-000000000014","11111111-0000-4000-8000-000000000019","11111111-0000-4000-8000-000000000012"]'::jsonb, null, 2),
  ('22222222-0000-4000-8000-000000000004', 'I''m applying', 'Put together a standout education application.', 'education', '["11111111-0000-4000-8000-000000000009","11111111-0000-4000-8000-000000000010","11111111-0000-4000-8000-000000000011"]'::jsonb, null, 3)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  domain = excluded.domain,
  template_ids = excluded.template_ids,
  checklist_template_id = excluded.checklist_template_id,
  display_order = excluded.display_order;
